[config] Clone meta-selinux at known good rev.
Using meta-selinux branch master as of this day will conflict with
oe-core jethro branch:
ERROR: No recipes available for
meta-selinux/recipes-extended/findutils/findutils_4.6.%.bbappend
meta-selinux/recipes-devtools/e2fsprogs/e2fsprogs_git.bbappend

Propositions to manage multiple layers configuration are already
discussed. Until that is done, resort to pick a fixed, compatible, rev.

Signed-off-by: Eric Chanudet <chanudete@ainfosec.com>